baseURL = "https://mhartkc.netlify.com/"
languageCode = "en-us"
title = "Monica Hart's Portfolio"
theme = "hugo-initio"
publishDir= "public"

[params]
    name = "Monica Hart"
    description = "An extra ordinary person"
    email = "mhart2012@gmail.com"
    address = "Mission, KS"
    year = 2020
    avatar = "img/avatarpic.jpg"
    banner = "img/grey_banner.jpg"
    gif = "img/pink_cat.gif"
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"
    404 = "404 Page Cannot Be Found"

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownload = true
    showClients = true

    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = true
    footerEnableFormWidget = true

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 5
[[menu.main]]
    name = "about"
    url = "/about/"
    weight = 5

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/monica.hart.33"
    icon = "fab fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/monica-hart12/"
    icon = "fab fa-linkedin"
    footer = false
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "github"
	url = "https://github.com/Mhart12"
    icon = "fab fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:mhart2012@gmai.com"
    icon = "fas fa-envelope-square"
    footer = false
    sharethis = true
    network = "email"

